name: buildx

on:
  push:
    branches:
      - "**"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker args
        id: docker_args
        run: |
          CONTEXT_PATH=.
          FILE_PATH=$CONTEXT_PATH/Dockerfile
          IMAGE=bxggs/mopidy

          BRANCH=${GITHUB_REF#refs/heads/}

          if [[ "$BRANCH" == "master" ]]; then
            TAG=latest
          else
            TAG="$(echo $BRANCH | sed -e 's/\//-/g')"
          fi

          echo "::set-output name=context_path::$CONTEXT_PATH"
          echo "::set-output name=file_path::$FILE_PATH"
          echo "::set-output name=tag::$IMAGE:$TAG"
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.docker_args.outputs.context_path }}
          file: ${{ steps.docker_args.outputs.file_path }}
          platforms: ${{ steps.buildx.outputs.platforms }}
          tags: ${{ steps.docker_args.outputs.tag }}
          push: true
